export const btntext=[
    {
        i0:"I",
        i1:"We",
        i2:"You",
        i3:"They",
        i4:"She"
    },
    {
        i0:"is",
        i1:"am",
        i2:"are",
        i3:"was",
        i4:"were"
    },
    {
        i0:"hungry",
        i1:"walkng",
        i2:"dancing",
        i3:"caring",
        i4:"loving"
    }
];